name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk upgrade
          apk add go git golangci-lint

      - uses: actions/checkout@v4

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v -count 1 $(go list ./... | grep -v '/internal/compress')

      - name: Test (race)
        run: go test -race -v -count 1 $(go list ./... | grep -v '/internal/compress')

      - name: Test (purego)
        run: go test -v -tags purego -count 1 $(go list ./... | grep -v '/internal/compress')

      - name: Lint
        run: golangci-lint run ./...

      - name: Vet
        run: go vet ./...

      - name: Format check
        run: test -z "$(gofmt -l .)"

      - name: Fix check
        run: test -z "$(go fix -diff ./...)"
